# Dataset Real Estate Listings (Data.World)

## Creating Folders

In [71]:
!echo "Creating data folder"
!mkdir -p data/bronze data/silver data/gold

Creating data folder

# Downloading Dataset

In [72]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/3ox2v5trynvowrhc27fjqkcx3lytjf?dws=00000')
df.to_csv("data/bronze/properati-BR-2016-11-01-properties-rent.csv", index=False)

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97353 entries, 0 to 97352
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   created_on                  97353 non-null  str
 1   operation                   97353 non-null  str
 2   property_type               97353 non-null  str
 3   place_name                  97353 non-null  str
 4   place_with_parent_names     97353 non-null  str
 5   geonames_id                 3 non-null      float64
 6   lat-lon                     46030 non-null  str
 7   lat                         46030 non-null  float64
 8   lon                         46030 non-null  float64
 9   price                       92334 non-null  float64
 10  currency                    92333 non-null  str
 11  price_aprox_local_currency  92334 non-null  float64
 12  price_aprox_usd             92334 non-null  float64
 13  surface_total_in_m2         15848 non-null  float64
 14  surface_covered_in_m2       75584 non-null  float64
 15  price_usd_per_m2            70415 non-null  float64
 16  price_per_m2                70415 non-null  float64
 17  floor                       5285 non-null   float64
 18  rooms                       58763 non-null  float64
 19  expenses                    31773 non-null  float64
 20  properati_url               97353 non-null  str
 21  description                 97353 non-null  str
 22  title                       97353 non-null  str
 23  image_thumbnail             92224 non-null  str
dtypes: float64(13), str(11)
memory usage: 17.8 MB

In [74]:
df.head()

,created_on,operation,property_type,place_name,place_with_parent_names,geonames_id,lat-lon,lat,lon,price,...,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url,description,title,image_thumbnail
0,2013-04-25,rent,apartment,Praia Grande,|Brasil|São Paulo|Praia Grande|,NaN,NaN,NaN,NaN,900.0,...,NaN,NaN,NaN,NaN,1.0,NaN,http://praia-grande-sao-paulo.properati.com.br...,"Otimo Imovel com o melhor valor da regiao, con...",Apartamento Em Praia Grande,NaN
1,2013-04-25,rent,apartment,Alphaville,|Brasil|São Paulo|Barueri|Alphaville|,NaN,NaN,NaN,NaN,3200.0,...,NaN,NaN,NaN,NaN,3.0,NaN,http://alphaville-barueri.properati.com.br/q8z...,"Otimo Imovel com o melhor valor da regiao, con...",Apartamento Em Barueri,https://thumbs-cf.properati.com/0/Wjq7toq-DpwK...
2,2013-04-25,rent,house,Centro,|Brasil|São Paulo|Jundiaí|Centro|,NaN,NaN,NaN,NaN,1800.0,...,NaN,NaN,NaN,NaN,2.0,NaN,http://centro-jundiai.properati.com.br/qe2_alu...,"Otimo Imovel com o melhor valor da regiao, con...",Casa Em Jundiai,NaN
3,2013-04-25,rent,apartment,Alphaville,|Brasil|São Paulo|Barueri|Alphaville|,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,http://alphaville-barueri.properati.com.br/s9p...,"Otimo Imovel com o melhor valor da regiao, con...",Apartamento Em Barueri,https://thumbs-cf.properati.com/0/X7PtsZjj8Vqz...
4,2013-04-25,rent,apartment,Barueri,|Brasil|São Paulo|Barueri|,NaN,NaN,NaN,NaN,1800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,http://barueri.properati.com.br/s9u_aluga-se_a...,"Otimo Imovel com o melhor valor da regiao, con...",Apartamento Em Barueri,https://thumbs-cf.properati.com/9/URn3U3gg-F6C...

## Cleaning (Silver)

## Split 'place' column

In [75]:
def split_place_with_parent_names(src_df):
    dst_df = src_df.copy()
    tmp_df = src_df['place_with_parent_names'].str.split("|", expand=True)

    dst_df['country'] = tmp_df[1]
    dst_df['region'] = tmp_df[2]
    dst_df['city'] = tmp_df[3]

    return dst_df

df_split = split_place_with_parent_names(df)
df_split

,created_on,operation,property_type,place_name,place_with_parent_names,geonames_id,lat-lon,lat,lon,price,...,floor,rooms,expenses,properati_url,description,title,image_thumbnail,country,region,city
0,2013-04-25,rent,apartment,Praia Grande,|Brasil|São Paulo|Praia Grande|,NaN,NaN,NaN,NaN,900.0,...,NaN,1.0,NaN,http://praia-grande-sao-paulo.properati.com.br...,"Otimo Imovel com o melhor valor da regiao, con...",Apartamento Em Praia Grande,NaN,Brasil,São Paulo,Praia Grande
1,2013-04-25,rent,apartment,Alphaville,|Brasil|São Paulo|Barueri|Alphaville|,NaN,NaN,NaN,NaN,3200.0,...,NaN,3.0,NaN,http://alphaville-barueri.properati.com.br/q8z...,"Otimo Imovel com o melhor valor da regiao, con...",Apartamento Em Barueri,https://thumbs-cf.properati.com/0/Wjq7toq-DpwK...,Brasil,São Paulo,Barueri
2,2013-04-25,rent,house,Centro,|Brasil|São Paulo|Jundiaí|Centro|,NaN,NaN,NaN,NaN,1800.0,...,NaN,2.0,NaN,http://centro-jundiai.properati.com.br/qe2_alu...,"Otimo Imovel com o melhor valor da regiao, con...",Casa Em Jundiai,NaN,Brasil,São Paulo,Jundiaí
3,2013-04-25,rent,apartment,Alphaville,|Brasil|São Paulo|Barueri|Alphaville|,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://alphaville-barueri.properati.com.br/s9p...,"Otimo Imovel com o melhor valor da regiao, con...",Apartamento Em Barueri,https://thumbs-cf.properati.com/0/X7PtsZjj8Vqz...,Brasil,São Paulo,Barueri
4,2013-04-25,rent,apartment,Barueri,|Brasil|São Paulo|Barueri|,NaN,NaN,NaN,NaN,1800.0,...,NaN,NaN,NaN,http://barueri.properati.com.br/s9u_aluga-se_a...,"Otimo Imovel com o melhor valor da regiao, con...",Apartamento Em Barueri,https://thumbs-cf.properati.com/9/URn3U3gg-F6C...,Brasil,São Paulo,Barueri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97348,2016-11-01,rent,apartment,Vila Adyana,|Brasil|São Paulo|São José dos Campos|Vila Ady...,NaN,NaN,NaN,NaN,1600.0,...,NaN,NaN,NaN,http://vila-adyana.properati.com.br/2hk0a_alug...,Apto em excelente localização com 3 dormitório...,Apto Vila AdyAna,https://thumbs-cf.properati.com/9/fO9avKeVE4nA...,Brasil,São Paulo,São José dos Campos
97349,2016-11-01,rent,apartment,Jardim Aquárius,|Brasil|São Paulo|São José dos Campos|Jardim A...,NaN,NaN,NaN,NaN,2000.0,...,NaN,NaN,NaN,http://jardim-aquarius.properati.com.br/2hk0b_...,"Apartamento novo com 2 dormitórios, sendo 1 su...",Apto Mobiliado Lindo Aquarius,https://thumbs-cf.properati.com/0/8vf7zRE3UU2K...,Brasil,São Paulo,São José dos Campos
97350,2016-11-01,rent,apartment,Jardim Aquárius,|Brasil|São Paulo|São José dos Campos|Jardim A...,NaN,NaN,NaN,NaN,1900.0,...,NaN,NaN,NaN,http://jardim-aquarius.properati.com.br/2hk0c_...,Apto novo no Jd. Aquarius ampla varanda gourme...,Lindo Apto Aquarius 2 vagas,https://thumbs-cf.properati.com/1/WGdWsXr0_NtM...,Brasil,São Paulo,São José dos Campos
97351,2016-11-01,rent,apartment,Votorantim,|Brasil|São Paulo|Votorantim|,NaN,NaN,NaN,NaN,900.0,...,NaN,1.0,301.0,http://votorantim-sao-paulo.properati.com.br/2...,Apartamento novíssimo no Ed. Alpha Club: - 2 d...,Apartamento para locação no Ed. Alpha Club,https://thumbs-cf.properati.com/1/8Lgn4c8Wj4eL...,Brasil,São Paulo,Votorantim
97352,2016-11-01,rent,apartment,Copacabana,|Brasil|Rio de Janeiro|Rio de Janeiro|Copacabana|,NaN,"-22.966091,-43.188034",-22.966091,-43.188034,1800.0,...,NaN,1.0,650.0,http://copacabana.properati.com.br/2hk0j_aluga...,SULMAR - Excelente apartamento em frente ao ho...,"Apartamento residencial para locação, Copacaba...",https://thumbs-cf.properati.com/0/zyBPyDLyQ7tW...,Brasil,Rio de Janeiro,Rio de Janeiro

## Remove unused columns

In [76]:
def remove_unused_colums(src_def):
    return df.drop(columns=[
        'place_name',
        'geonames_id',
        'place_name',
        'place_with_parent_names',
        'lat-lon',
        'currency',
        'price_aprox_local_currency',
        'expenses',
        'properati_url',
        'description',
        'title',
        'image_thumbnail']
    )

df_less_columns = remove_unused_colums(df_split)
df_less_columns.info()

<class 'pandas.DataFrame'>
RangeIndex: 97353 entries, 0 to 97352
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   created_on             97353 non-null  str
 1   operation              97353 non-null  str
 2   property_type          97353 non-null  str
 3   lat                    46030 non-null  float64
 4   lon                    46030 non-null  float64
 5   price                  92334 non-null  float64
 6   price_aprox_usd        92334 non-null  float64
 7   surface_total_in_m2    15848 non-null  float64
 8   surface_covered_in_m2  75584 non-null  float64
 9   price_usd_per_m2       70415 non-null  float64
 10  price_per_m2           70415 non-null  float64
 11  floor                  5285 non-null   float64
 12  rooms                  58763 non-null  float64
dtypes: float64(10), str(3)
memory usage: 9.7 MB

## Count # of NaN values

In [77]:
df_less_columns.isna().sum()

created_on                   0
operation                    0
property_type                0
lat                      51323
lon                      51323
price                     5019
price_aprox_usd           5019
surface_total_in_m2      81505
surface_covered_in_m2    21769
price_usd_per_m2         26938
price_per_m2             26938
floor                    92068
rooms                    38590
dtype: int64

In [78]:
def replace_empty_values(src_df):
    dst_df = src_df.copy()
    # dst_df["geonames_id"] = src_df["geonames_id"].fillna(0)
    # dst_df["lat-lon"] = src_df["lat-lon"].fillna("")
    dst_df["lat"] = src_df["lat"].fillna(0)
    dst_df["lon"] = src_df["lon"].fillna(0)

    dst_df["price"] = src_df["price"].fillna(0)
    # dst_df["currency"] = src_df["currency"].fillna("")
    
    # dst_df["price_aprox_local_currency"] = src_df["price_aprox_local_currency"].fillna(0)
    dst_df["price_aprox_usd"] = src_df["price_aprox_usd"].fillna(0)
    dst_df["surface_total_in_m2"] = src_df["surface_total_in_m2"].fillna(0)
    dst_df["surface_covered_in_m2"] = src_df["surface_covered_in_m2"].fillna(0)
    dst_df["price_usd_per_m2"] = src_df["price_usd_per_m2"].fillna(0)
    dst_df["price_per_m2"] = src_df["price_per_m2"].fillna(0)

    dst_df["floor"] = src_df["floor"].fillna(0)
    dst_df["rooms"] = src_df["rooms"].fillna(0)

    # dst_df["expenses"] = src_df["expenses"].fillna(0)
    # dst_df["image_thumbnail"] = src_df["image_thumbnail"].fillna("")


    return dst_df

df_filled = replace_empty_values(df_less_columns)
df_filled.isna().sum()

created_on               0
operation                0
property_type            0
lat                      0
lon                      0
price                    0
price_aprox_usd          0
surface_total_in_m2      0
surface_covered_in_m2    0
price_usd_per_m2         0
price_per_m2             0
floor                    0
rooms                    0
dtype: int64

## Drop entries without price

In [79]:
def drop_entries_without_price(src_df):
    return src_df[src_df["price"] != 0].copy()

df_priced = drop_entries_without_price(df_filled)
df_priced

,created_on,operation,property_type,lat,lon,price,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms
0,2013-04-25,rent,apartment,0.000000,0.000000,900.0,280.84,0.0,0.0,0.000000,0.000000,0.0,1.0
1,2013-04-25,rent,apartment,0.000000,0.000000,3200.0,998.56,0.0,0.0,0.000000,0.000000,0.0,3.0
2,2013-04-25,rent,house,0.000000,0.000000,1800.0,561.69,0.0,0.0,0.000000,0.000000,0.0,2.0
4,2013-04-25,rent,apartment,0.000000,0.000000,1800.0,561.69,0.0,0.0,0.000000,0.000000,0.0,0.0
6,2013-04-25,rent,apartment,0.000000,0.000000,2000.0,624.10,0.0,0.0,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97348,2016-11-01,rent,apartment,0.000000,0.000000,1600.0,499.28,0.0,0.0,0.000000,0.000000,0.0,0.0
97349,2016-11-01,rent,apartment,0.000000,0.000000,2000.0,624.10,0.0,0.0,0.000000,0.000000,0.0,0.0
97350,2016-11-01,rent,apartment,0.000000,0.000000,1900.0,592.89,0.0,0.0,0.000000,0.000000,0.0,0.0
97351,2016-11-01,rent,apartment,0.000000,0.000000,900.0,280.84,0.0,0.0,0.000000,0.000000,0.0,1.0
97352,2016-11-01,rent,apartment,-22.966091,-43.188034,1800.0,561.69,0.0,33.0,17.020909,54.545455,0.0,1.0

## Update USD values

In [80]:
USD_TO_BRL = 5.06 # 1 USD = X BRL

def update_usd_values(src_df):
    dst_df = src_df.copy()

    usd_price = src_df['price'] / USD_TO_BRL
    dst_df['price_aprox_usd'] = usd_price

    valid_surface = src_df['surface_covered_in_m2'] > 0
    dst_df.loc[valid_surface, 'price_usd_per_m2'] = usd_price / src_df['surface_covered_in_m2']

    return dst_df

df_usd = update_usd_values(df_priced)
df_usd

,created_on,operation,property_type,lat,lon,price,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms
0,2013-04-25,rent,apartment,0.000000,0.000000,900.0,177.865613,0.0,0.0,0.000000,0.000000,0.0,1.0
1,2013-04-25,rent,apartment,0.000000,0.000000,3200.0,632.411067,0.0,0.0,0.000000,0.000000,0.0,3.0
2,2013-04-25,rent,house,0.000000,0.000000,1800.0,355.731225,0.0,0.0,0.000000,0.000000,0.0,2.0
4,2013-04-25,rent,apartment,0.000000,0.000000,1800.0,355.731225,0.0,0.0,0.000000,0.000000,0.0,0.0
6,2013-04-25,rent,apartment,0.000000,0.000000,2000.0,395.256917,0.0,0.0,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97348,2016-11-01,rent,apartment,0.000000,0.000000,1600.0,316.205534,0.0,0.0,0.000000,0.000000,0.0,0.0
97349,2016-11-01,rent,apartment,0.000000,0.000000,2000.0,395.256917,0.0,0.0,0.000000,0.000000,0.0,0.0
97350,2016-11-01,rent,apartment,0.000000,0.000000,1900.0,375.494071,0.0,0.0,0.000000,0.000000,0.0,0.0
97351,2016-11-01,rent,apartment,0.000000,0.000000,900.0,177.865613,0.0,0.0,0.000000,0.000000,0.0,1.0
97352,2016-11-01,rent,apartment,-22.966091,-43.188034,1800.0,355.731225,0.0,33.0,10.779734,54.545455,0.0,1.0

In [81]:
df_usd.info()

<class 'pandas.DataFrame'>
Index: 92332 entries, 0 to 97352
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   created_on             92332 non-null  str
 1   operation              92332 non-null  str
 2   property_type          92332 non-null  str
 3   lat                    92332 non-null  float64
 4   lon                    92332 non-null  float64
 5   price                  92332 non-null  float64
 6   price_aprox_usd        92332 non-null  float64
 7   surface_total_in_m2    92332 non-null  float64
 8   surface_covered_in_m2  92332 non-null  float64
 9   price_usd_per_m2       92332 non-null  float64
 10  price_per_m2           92332 non-null  float64
 11  floor                  92332 non-null  float64
 12  rooms                  92332 non-null  float64
dtypes: float64(10), str(3)
memory usage: 11.9 MB

In [83]:
df_usd.to_csv('data/silver/properati-BR-2016-11-01-properties-rent.csv', index=False)